feat: retry x times if unable to find pom data
status-im/go-maven-resolver pull request #7
Opened 2024-01-19 16:43 UTC by siddarthkay

As seen here : https://github.com/status-im/status-mobile/issues/18294 and multiple times locally, 
sometimes `make nix-update-gradle` fails to get pom data for this gradle dependency : https://plugins.gradle.org/plugin/com.adarshr.test-logger/2.0.0 

Running `make nix-update-gradle` again fixes it, sometimes it takes more than a single retry to fix.

This PR introduces a minimum of 3 retries if go-maven-resolver fails to resolve a dependency due to networking issues that could potentially be caused by concurrent threads.

This is just a suggestion and my not fix the problem for good, but I wanted your opinion on this @jakubgs and hence I opened this PR.

2024-01-21 05:04 UTC, siddarthkay commented
I at first kept `retryDelay` to 2 seconds and although i didn't get any error but it was taking a lot of time to run `make nix-update-gradle` , I manually terminated the process after it was > 30 mins.

I then updated  `retryDelay`  to half a second and get errors like this : 

```
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while 
reading body)' for: <Dep ID=io.netty:netty-parent:4.1.34.Final O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while 
reading body)' for: <Dep ID=org.apache.commons:commons-parent:32 O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while 
reading body)' for: <Dep ID=com.sun.activation:all:1.2.0 O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while 
reading body)' for: <Dep ID=io.netty:netty-parent:4.1.72.Final O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while 
reading body)' for: <Dep ID=io.netty:netty-parent:4.1.52.Final O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while 
reading body)' for: <Dep ID=com.sun.activation:all:1.2.1 O=false S= >
```

2024-01-21 06:57 UTC, siddarthkay commented
After keeping delay of 1 second, `make nix-upgrade-gradle` ran fine but took 40 minutes 🥲🥲🥲
And then later when i added one more gradle dep manually, its been failing with errors like this : 

```
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while reading 
body)' for: <Dep ID=org.apache.commons:commons-parent:52 O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while reading 
body)' for: <Dep ID=org.apache.commons:commons-parent:33 O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while reading 
body)' for: <Dep ID=org.apache.commons:commons-parent:39 O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while reading 
body)' for: <Dep ID=org.apache.commons:commons-parent:48 O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while reading 
body)' for: <Dep ID=net.sf.proguard:proguard-parent:5.2.1 O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while reading 
body)' for: <Dep ID=org.codehaus.mojo:mojo-parent:34 O=false S= >
finder.go:138: error: 'context deadline exceeded (Client.Timeout or context cancellation while reading 
body)' for: <Dep ID=org.codehaus.mojo:mojo-parent:50 O=false S= >
```

so probably this change is not such a good idea :)

2024-01-22 02:28 UTC, siddarthkay commented
> but took 40 minutes

could also be because of hotel wifi,
I'll check on another network and update here.

2024-01-25 09:18 UTC, siddarthkay commented
yeah right the 40mins was due to bad wifi, it takes 9 minutes now

2024-01-29 11:47 UTC, jakubgs requested changes
You are embedding magic constants into the `finder` modules. This is not how things should be done. Look at the `Options` struct that contains things like `IgnoreOptional` or `RecursiveSearch`. Clearly these settings should be added there as `retryAttempts` and `retryDelayMsec` to allow for configuration at runtime via CLI flags.

Secondly, why are you adding retries here if the `fetcher` module already has retries implemented?
https://github.com/status-im/go-maven-resolver/blob/bd9da57e5ee35bbc79f20050dab14dad74afbd29/fetcher/fetcher.go#L70-L72

2026-01-20 19:01 UTC, siddarthkay commented
closing as no longer needed.

2026-01-20 19:01 UTC, closed without merging